name: Sync Changes to Fork

on:
  pull_request:
    types:
      - closed

jobs:
  sync_fork:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout foo repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Sync Fork
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
        run: |
          BASE_BRANCH=${{ github.event.pull_request.base.ref }}
          gh repo sync adskyiproger/poc-core-test-my --branch ${BASE_BRANCH}

