name: Get everything from slack

on:
  push


permissions:
  contents: write

jobs:
  sync_farajaland:
    runs-on: ubuntu-latest
    env:
      UPSTREAM_REPOSITORY: ${{ github.repository }}
      BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
      # Check token under Olli's account
      GH_TOKEN: ${{ secrets.FORK_ORGANISATION_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FORK_REPOSITORY_PATH: "${{ vars.FORK_REPOSITORY_ORGANISATION }}/${{ vars.FORK_REPOSITORY_NAME }}"
    steps:
      - name: Send slack notification
        run: |
          curl -X GET https://slack.com/api/users.list \
            -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}"
          BODY="Hello, this is a test message from GitHub Actions by <@D08BV0CR5GW>!"
          curl -X POST https://slack.com/api/chat.postMessage \
          -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
          -H 'Content-type: application/json' \
          --data "{
            'channel': 'C08FCLKER8X',
            'text': '$BODY'
          }"
